### PR TITLE
Course Registration FE

### LINKED ISSUE #795: [ Course Onboarding ] -- Frontend of the Course Registration Endpoint
This is a bit of a huge task, but I don't know how to split it up otherwise. 

**Your Mission** -- Implement the frontend designs for course registration found in [the Figma](https://www.figma.com/file/AXOFBPj7DEIhYyAVe9AIil/In-Progress?node-id=286%3A3474). It can be relatively unstyled for now (we can worry about that later), but make it intuitive. 

Notes:
- Display name validation - no need for regex, but put a character limit (like 20 chars)
- Once the professor logs in, we will have an attribute `pending courses` in the GET Profile response if they are a professor. If we receive that in the payload, we want to redirect to the registration flow. THIS SEEMS TRICKY. 
- Once the professor makes it all the way through the frontend flow, hit the course registration endpoint outlined by #780 . 

Refer to the notion doc or let us know if you want more clarification. Good luck soldier

### PR DESCRIPTION
**Pull request by IrisLiu-00**
# Description
Creates the frontend for course registration, including the apply page and the automatic redirect to the apply page. 

Closes #795 

Overview of technical changes:
- Altered `useTodayPageRedirect` hook to `useHomePageRedirect` - in addition to redirecting the user to the /today page of their default course, it will redirect the user to the /apply page if they have any pending courses in their profile
- Replaced the old course application page with the new application flow, outlined in [figma designs](https://www.figma.com/file/AXOFBPj7DEIhYyAVe9AIil/In-Progress?node-id=286%3A3474)
- This needs #801 to be merged first so the frontend can be hooked up to the course_registration endpoint

## Type of change

Please delete options that are not relevant.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

You can manually test this if you fake some admin data in psql. Make sure you have the latest DB migrations, and the profId should be the ID of the professor (Edward Li) in your DB.
```
 insert into last_registration_model ("profId", "lastRegisteredSemester") values (5, '202030'); 
 
 insert into prof_section_groups_model ("profId", "sectionGroups") values (5, '[
      {
        "name": "Fundies 3",
        "crns": [123, 456],
        "semester": "202110"
      },
      {
        "name": "OOD",
        "crns": [798],
        "semester": "202110"
      }
    ]');
```
Once the data is populated, logging in as a prof should automatically redirect you into the apply flow (if not, navigating to /nocourses should trigger the redirect).

# Screenshots:
image
image
image
image

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by nicoledanuwidjaja** [comment]
Nice nice nice! Didn't find any strange cases.
Screen Shot 2022-01-09 at 1 17 42 AM
Maybe one thing would be that if no courses are submitted, perhaps it shouldn't allow the prof to click on the Next button.

**Comment by IrisLiu-00** [comment]
> Maybe one thing would be that if no courses are submitted, perhaps it shouldn't allow the prof to click on the Next button. Similarly, I think the container under "The following courses have already registered for the app:" looks funky when there are no courses registered.

We actually purposefully allowed profs to not select any courses, because there's the possibility that other profs/ course coordinators have already registered their courses for them. But that's a good point about the confirmation page looking weird, I did a lazy change  so it shows a custom message if you haven't selected anything: 
image

**Review by nicoledanuwidjaja — APPROVED** [review]
✨✨

**Review by dfarooq610 — APPROVED** [review]
Nice!!! Everything looks solid to me

**Pull request merged**
