### PR TITLE
Ta add students

### PR DESCRIPTION
**Pull request by wskksw**
# Description

Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Closes # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dfarooq610** [comment]
Hi @wskksw! 

I see that you have recently forked the app for development and adaptation at UBC Okanagan, which is really cool! That is part of the reason we made the code open-source. i'm glad you find that it's a valuable tool, and are taking the time to adapt the product to your specific use case. 

Since you are operating on a fork, I assume that you have mistakenly made this PR. That is totally fine! Let me know if that is not the case. 

Also, i think it would be really cool to talk about some of your long-term visions for modifying the app, and see if we can do anything on our end to make that an easier process for you. 

Lmk if you have any questions, concerns, compliments or qualms!

Best, 
Danish

**Comment by wskksw** [comment]
Oh yeah I am really sorry, that was an accident, didn't mean to do this! Sorry!

**Comment by wskksw** [comment]
And also, yes it is a very cool web app that we will use for 2 of the courses here by a very caring professor. Thank you for developing it!

**Comment by wskksw** [comment]
My email is kevinwang1262000@gmail.com if you want to learn about what I am doing with the app and our specific use cases here!

**Pull request closed without merging**
