### PR TITLE
WIP: Question Grouping Frontend

### PR DESCRIPTION
**Pull request by IrisLiu-00**
# Description

Implements the frontend for question grouping (issue #621)  
This is a WIP so there's still a lot of TODOs in the code for hooking things up with the backend. 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Manually: hit `Add Students` under the question grouping sidebar, add some students, then hit the call button to get the second view

(Students currently in a group do not show up on the sidebar, because the group is not actually created on the backend and would need to be passed into the `TAQueueListSection`)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by liustanley** [comment]
Looks great! My only comments are:
- [ ] It would be nice if the blue highlight and the bottom line when you select someone for grouping extended all the way, but if this turns out to be ridiculous to implement it's all good
- [ ] This is my bad because I forgot to include it in the story mockups, but we want an additional form option when the student is creating/editing a question. The form option should be "Would you like the option of being helped in a group session?", with Yes and No options. It can also have a description saying "Clicking Yes may result in a shorter wait time if others have the same question as you."

Since I forgot to include the second one, it's ok if you want to wait until next sprint to implement it

**Comment by liustanley** [comment]
Oh one more thing:
- [ ] Instead of the "Remove from Queue" option below, we want the "Requeue" and "Can't Find" buttons

Screen Shot 2021-03-17 at 7 18 55 PM

**Comment by IrisLiu-00** [comment]
> * [ ]  Instead of the "Remove from Queue" option below, we want the "Requeue" and "Can't Find" buttons

Someone can correct me if I'm wrong on this, but I believe that will have the proper buttons once the backend is hooked up - I'm using the `TAQueueDetailButtons`, which will show different buttons depending on the question status. I didn't do any backend calls to change questions statuses when you hit the call button, although maybe I should have put something 🤔 

> * [ ]  It would be nice if the blue highlight and the bottom line when you select someone for grouping extended all the way, but if this turns out to be ridiculous to implement it's all good

Yeah I didn't do this at first because I thought it would be nasty but it's not all that nasty actually. Should be fixed now

> * [ ] This is my bad because I forgot to include it in the story mockups, but we want an additional form option when the student is creating/editing a question. The form option should be "Would you like the option of being helped in a group session?", with Yes and No options. It can also have a description saying "Clicking Yes may result in a shorter wait time if others have the same question as you."

Oops we will do this, although it may take a few extra days before I get around to it !!

**Review by liustanley — APPROVED** [review]

**Comment by willstenzel** [comment]
> Oh one more thing:
> 
> * [ ]  Instead of the "Remove from Queue" option below, we want the "Requeue" and "Can't Find" buttons
> 
> Screen Shot 2021-03-17 at 7 18 55 PM

@liustanley does it make sense to have all three buttons ("Remove from Queue", "Requeue", "Can't Find") here? Or is there a reason to only have the "Requeue" and "Can't Find" buttons?

**Pull request closed without merging**
