### PR TITLE
move create queue flow to check in button

### LINKED ISSUE #877: Move Create Queue button to Check In modal
It's confusing to have 2 buttons on the today page, so Ally Chao (who has a 10x larger brain than any of us) suggested putting the Create Queue button into the checkin modal. This way you can try to checkin, see that there's no matching queue, and then create a new queue.

### PR DESCRIPTION
**Pull request by dfarooq610**
# Description
Moves the create queue flow to the check in button, and deletes the queue create button on the today page. We now have only one magic button to deal with all queue management.

Notes: 
- if a course has no queues, auto launch the create queue modal
- adds a create queue button to the check in modal, which launches the create queue modal (and closes the check in modal)

i hope this code is considered `clean` and ty to sumit for bearing with me while i stream-of-consiousness coded

Closes #877 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Manually (this is about to break some cypress tests i know)
- [ ] Check in to a queue as normal (expect to see a create queue button there but do not engage)
https://user-images.githubusercontent.com/59672089/165001209-c4c8afd3-a25e-4799-81af-1134bc9d0bcf.mov
- [ ] With queues present, try to create a new queue by clicking the create queue button
https://user-images.githubusercontent.com/59672089/165001261-fbcb309a-a004-4b53-96c8-2a83e3f837d8.mov
- [ ] disable all queues, expect to launch a create queue modal, and successfully create it 
https://user-images.githubusercontent.com/59672089/165001296-e408e17a-9e71-4ddb-9ac8-4dfe9dc345b4.mov

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by VKong6019** [comment]
just gonna put it here for the logs: briefly talked on [slack ](https://sandboxneu.slack.com/archives/C012VU1BYRF/p1650835289765319)about `Create Queue` button placement

**Comment by dfarooq610** [comment]
https://user-images.githubusercontent.com/59672089/165105423-f7b3268c-d60c-493a-8603-3cf0d83597bb.mov

@VKong6019 does this look good to you?

**Comment by dfarooq610** [comment]
it might be the vercel deploy? i dont seem to be running into any issues locally

**Review by IrisLiu-00 — APPROVED** [review]
aight yeah i actually couldnt reproduce the bug on vercel either soo idk lol. this is sick otherwise!

**Review by VKong6019 — APPROVED** [review]
Yeet

**Pull request merged**
