### PR TITLE
Settings Part 2: Profile page

### PR DESCRIPTION
**Pull request by NEUDitao**

### CODE REVIEW

**Review by dajinchu — APPROVED** [review]
Good but whats with the space here between the lines
image

**Comment by NEUDitao** [comment]
@dajinchu just fixed the vertical line, lmk your new opinions

**Review by willstenzel — APPROVED** [review]
Solid PR

**Review by dajinchu — APPROVED** [review]

**Comment by willstenzel** [comment]
Also you'll want to update the `onClick` for this notification so it will still work as expected. 

https://github.com/sandboxnu/office-hours/blob/a834200593e1c6ed99c00149428c91570d0789f3/packages/app/components/Queue/Student/StudentQueueList.tsx#L202-L215

**Pull request merged**
