### PR TITLE
About Page

### LINKED ISSUE #610: About page
Want to design and create a page that contains details on:
- [ ] Khoury Office Hours team members
- [ ] Short description of the app and its history

Can include the About page as an option in the profile dropdown

### PR DESCRIPTION
**Pull request by IrisLiu-00**
# Description

Creates an about page for the app. 

Closes #610 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Manually: navigate to about page through the dropdown on your user profile (choose the "About Us" option). look at the page with your eyeballs and test out the links

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by NEUDitao** [comment]
Will looks a little silly, if you could move him up or crop him a little that'd be great but other than that LGTM

**Review by willstenzel — APPROVED** [review]
Great stuff, thanks for putting this together!

**Review by liustanley — APPROVED** [review]
looks so clean!!! let's merge after linting is fixed.

also a suggestion: should we hyperlink `students` in the footer to `/about` for more visibility?

**Comment by IrisLiu-00** [comment]
Oh yeah, I think the linting errors are because of changes on master to disable requestion - it's mostly stuff about unused imports because the requestion components are commented out. I didn't want to fix it because I assume we will need to use those imports once requestion is put back - should I just leave it since it's not a required check?

> also a suggestion: should we hyperlink `students` in the footer to `/about` for more visibility?
 
done in the latest commit ✔️

**Pull request merged**
