### PR TITLE
Date filters for insights page

### LINKED ISSUE #577: Data insight filters pane

### PR DESCRIPTION
**Pull request by willstenzel**
# Description

This PR adds the ability to filter the insights data by a specified date range. 

Closes #577 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This PR was tested manually by seeding the data and trying different date ranges that include or don't include the start date of the seeded data. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code where needed 
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by willstenzel** [comment]
**Updated UI**

image

**Review by liustanley — APPROVED** [review]
Looks nice! I'm having trouble testing locally though, getting a `304` on `GET /api/v1/insights/list`

**Comment by liustanley** [comment]
Also might be good to merge master into this branch just to get tests working

**Review by NEUDitao — APPROVED** [review]

**Comment by liustanley** [comment]
UI looks great and seems to work! One suggestion I have is to move the date range input onto the same line as the `Insights Dashboard` header, aligned to the right. Like so: https://cdn.dribbble.com/users/1852474/screenshots/14472838/media/cead1de9f8cac7c2e0b95bce7e258fb4.mp4

**Comment by willstenzel** [comment]
> UI looks great and seems to work! One suggestion I have is to move the date range input onto the same line as the `Insights Dashboard` header, aligned to the right. Like so: https://cdn.dribbble.com/users/1852474/screenshots/14472838/media/cead1de9f8cac7c2e0b95bce7e258fb4.mp4

Great idea. I'll add that when I get a chance

**Pull request merged**
